from sqlalchemy import Column, Integer, BigInteger, SmallInteger, String, Numeric, Date, Time
from typing import Optional
from datetime import date, time
from .database import Base


class HeadOfSpecifications(Base):
    __tablename__ = 'ka2450_00105'
    __allow_unmapped__ = True
    
    KA2450_REZ_NR = Column(BigInteger, primary_key=True, nullable=False)
    KA2450_VAR_NR = Column(SmallInteger, primary_key=True, nullable=False)
    KA2450_REZ_OBJ_TYP = Column(SmallInteger, primary_key=True, nullable=False)
    KA2450_REZ_OBJ_NR = Column(BigInteger, primary_key=True, nullable=False)

    KA2450_REZ_AKTIV_VON = Column(Integer, nullable=False)
    KA2450_REZ_AKTIV_BIS = Column(Integer, nullable=False)
    KA2450_ANL_DATUM = Column(Integer, nullable=False)
    KA2450_ANL_ZEIT = Column(Integer, nullable=False)
    KA2450_ANL_USER = Column(Integer, nullable=False)
    KA2450_ANL_STATION = Column(SmallInteger, nullable=False)
    KA2450_ANL_PROG = Column(SmallInteger,nullable=False)
    KA2450_ANL_FKT = Column(Integer, nullable=False)
    KA2450_UPD_DATUM = Column(Integer, nullable=False)
    KA2450_UPD_ZEIT = Column(Integer, nullable=False)
    KA2450_UPD_USER = Column(Integer, nullable=False)
    KA2450_UPD_STATION = Column(SmallInteger, nullable=False)
    KA2450_UPD_PROG = Column(SmallInteger, nullable=False)
    KA2450_UPD_FKT = Column(Integer,nullable=False)
    KA2450_VAR_BEZ = Column(String(50), nullable=False)
    KA2450_REZ_VERANT_USER = Column(Integer, nullable=False)
    KA2450_PROD_KST_NR = Column(BigInteger, nullable=False)
    KA2450_KALK_DATUM = Column(Integer, nullable=False)
    KA2450_KALK_DATUM_NACHK = Column(Integer, nullable=False)
    KA2450_KALK_DATUM_GLOBAL = Column(Integer, nullable=False)
    KA2450_NACHKALK_PROG_NR = Column(SmallInteger,nullable=False)
    KA2450_PROD_ZUL_DATUM_VON = Column(Integer, nullable=False)
    KA2450_PROD_ZUL_DATUM_BIS = Column(Integer, nullable=False)
    KA2450_BEZUGSDATUM_VAR_ERM = Column(Integer, nullable=False)
    KA2450_GES_GEW_SGE = Column(Numeric(18, 6),nullable=False)
    KA2450_GES_GEW_PE_VK = Column(Numeric(18, 6), nullable=False)
    KA2450_GES_GEW_SGE_BRU = Column(Numeric(18, 6), nullable=False)
    KA2450_GES_STUECKZAHL = Column(Numeric(18, 6),nullable=False)
    KA2450_CHAR_GR_PE_VK = Column(Numeric(18, 6), nullable=False)
    KA2450_MIN_CHAR_GR_PE_VK = Column(Numeric(18, 6), nullable=False)
    KA2450_SUM_ANT_MENGE_SGE = Column(Numeric(18, 6), nullable=False)
    KA2450_PREISSTUFE_MAT = Column(SmallInteger, nullable=False)
    KA2450_PREISSTUFE_EIN = Column(SmallInteger, nullable=False)
    KA2450_PREISSTUFE_REN = Column(SmallInteger, nullable=False)
    KA2450_PREISSTUFE_VK = Column(SmallInteger,nullable=False)
    KA2450_SPERRE = Column(SmallInteger, nullable=False)
    KA2450_REZ_TYP = Column(SmallInteger, nullable=False)
    KA2450_STUECK_KALK = Column(SmallInteger, nullable=False)
    KA2450_LINIENFERTIGUNG = Column(SmallInteger, nullable=False)
    KA2450_ALT_PROD_VAR = Column(SmallInteger,nullable=False)
    KA2450_VK_REZ = Column(SmallInteger, nullable=False)
    KA2450_EXPORT_EXTERN = Column(SmallInteger, nullable=False)
    KA2450_KALK_BASIS = Column(SmallInteger,nullable=False)
    KA2450_QUID_BERECHNUNG = Column(SmallInteger, nullable=False)
    KA2450_HERST_DAUER = Column(Numeric(17, 4), nullable=False)
    KA2450_HERST_DAUER_EINMALIG = Column(Numeric(17, 4), nullable=False)
    KA2450_RUEST_DAUER = Column(Numeric(17, 4), nullable=False)
    KA2450_LIEGE_DAUER = Column(Numeric(17, 4), nullable=False)
    KA2450_ZIELTEMPERATUR = Column(Numeric(11, 6),  nullable=False)
    KA2450_TEMP_VERAEND_ABS = Column(Numeric(11, 6),  nullable=False)
    KA2450_TEMP_KORR_FAKTOR = Column(Numeric(11, 6), nullable=False)
    KA2450_LA_STATUS_VERW = Column(SmallInteger,  nullable=False)
    KA2450_LA_STATUS_NR = Column(SmallInteger, nullable=False)
    KA2450_DICHTE = Column(Numeric(11, 6),  nullable=False)
    KA2450_SPEZ_NR = Column(BigInteger, nullable=False)
    KA2450_RKL_AUSPR_NR_1 = Column(BigInteger, nullable=False)
    KA2450_RKL_AUSPR_NR_2 = Column(BigInteger,  nullable=False)
    KA2450_RKL_AUSPR_NR_3 = Column(BigInteger,  nullable=False)
    KA2450_RKL_AUSPR_NR_4 = Column(BigInteger,nullable=False)
    KA2450_RKL_AUSPR_NR_5 = Column(BigInteger, nullable=False)
    KA2450_PROZ_BASIS_MENGE = Column(Numeric(9, 6), nullable=False)
    KA2450_OPT_ART_LST_NR = Column(BigInteger, nullable=False)
    KA2450_CIM_NR = Column(BigInteger, nullable=False)
    KA2450_VERF_NR = Column(BigInteger, nullable=False)
    KA2450_ALT_KST_LST_NR = Column(BigInteger, nullable=False)
    KA2450_ANZ_ETIKETTEN = Column(BigInteger,    nullable=False)
    KA2450_REZ_VERS_NR = Column(BigInteger,   nullable=False)
    KA2450_DET_SPERR_STAT = Column(Integer, nullable=False)
    KA2450_HBK_ZEIT = Column(Numeric(5, 1),  nullable=False)
    KA2450_PREIS_ERM = Column(SmallInteger, nullable=False)
    KA2450_BEZUG_DAT_PREIS_ERM = Column(Integer, nullable=False)
    KA2450_PREISBILDUNG = Column(SmallInteger, nullable=False)
    KA2450_GS_VAR = Column(SmallInteger,nullable=False)
    KA2450_VERS_EXT = Column(BigInteger, nullable=False)
    KA2450_PREIS_FORT_VAR = Column(SmallInteger, nullable=False)
    
    def __repr__(self):
        return f"<HeadOfSpecifications(REZ_NR={self.KA2450_REZ_NR}, VAR_NR={self.KA2450_VAR_NR})>"